services:
  app:
    tty: true
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "tkycraft/mahirun:ruby3-rails7-0.0.1"
    container_name: mahirun-server
    volumes:
      - .:/opt/app/
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-m", "5", "http://localhost:3000"]
      interval: 15s
      timeout: 5s
      retries: 4
      start_period: 10s

  keycloak:
    tty: true
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
      - KC_DB_URL_DATABASE=keycloak
      - KC_HOSTNAME_STRICT='false'
      - KC_HTTP_ENABLED='true'
      - KC_HOSTNAME_STRICT_HTTPS='false'
    ports:
      - 8080:8080
    command:
      # - "start"
      - "start-dev"   # on development mode.

  mysql:
    image: mysql:8.1.0-oracle   # arm image (only oracle linux base)
    container_name: mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=keycloak
    ports:
      - 3306:3306
    volumes:
      - mysql-store:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$MYSQL_DATABASE", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s

volumes:
  mysql-store:
