name: Rspec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.1.0-oracle
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
    env: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_test
    steps:
    - uses: actions/checkout@v4
    - name: build and create DB
      shell: bash
      run: |
        docker-compose -f compose.yaml -f compose.rspec.yaml build
        docker-compose -f compose.yaml -f compose.rspec.yaml run app rails db:create
      env:
        RAILS_ENV: test
    - name: exec rspec
      run:  |
        docker-compose -f compose.yaml -f compose.rspec.yaml run app bundle exec rspec
      env:
        RAILS_ENV: test
